version: '3'
services:
  app:
    container_name: ze_code_prj
    restart: always
    build: .
    ports:
      - '3000:3000'
    volumes: ['./:/usr/src/app']
    links:
      - mongo
  mongo:
    container_name: db_mongo_ze
    image: mongo
    ports:
      - '27017:27017'
